config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  root "home#index"

  resources :food_items
  resources :meals
  resources :recipes do
    resources :ingredients
  end
  resources :meal_plans do
    resources :meal_plan_days
    resources :shopping_basket_items
  end
  resources :meal_plan_days do
    resources :meals
  end
  post '/meal_plan_days/:id/copy', to: 'meal_plan_days#copy', as: 'copy_meal_plan_day'
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  has_many :meal_plan_days, dependent: :destroy
  has_many :shopping_basket_items, dependent: :destroy

  validates :date_range, presence: true

  def shopping_list_items
      result = []
      self.meal_plan_days.each do |meal_plan_day|
        meal_plan_day.meals.each do |meal|
          meal.recipe.ingredients.each do |ingredient|
            quantity = ingredient.quantity_per_serving * meal.servings
            item_data = result.find do |item|
              item[:food_item_id] == ingredient.food_item_id
            end
            if !item_data
              result << {
                food_item_id: ingredient.food_item.id,
                food_item_name: ingredient.food_item.name,
                food_item_unit: ingredient.food_item.unit,
                quantity: quantity,
              }
            else
              item_data[:quantity] += quantity
            end
          end
        end
      end
      self.shopping_basket_items.each do |shopping_basket_item|
        item_data = result.find do |item|
          item[:food_item_id] == shopping_basket_item.food_item_id
        end
        item_data[:shopping_basket_item] = shopping_basket_item
      end
      result
  end
end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
  def index
    @meal_plans = MealPlan.all
  end

  def show
    @meal_plan = MealPlan.find(params[:id])
    @hide_items_in_basket = params[:hide_items_in_basket] == 'true'
  end

  def new
    @meal_plan = MealPlan.new
  end

  def create
    @meal_plan = MealPlan.new(new_meal_plan_params)

    if @meal_plan.save
      @meal_plan.date_range.each { |date|
        @meal_plan.meal_plan_days.create(date: date)
      }
      redirect_to @meal_plan
    else
      render :new
    end
  end

  def edit
    @meal_plan = MealPlan.find(params[:id])
  end

  def update
    @meal_plan = MealPlan.find(params[:id])

    params[:meal_plan_day].each do |id, meal_plan_day_params|
      meal_plan_day = MealPlanDay.find(id)
      if !meal_plan_day.update(meal_plan_day_params.permit(:note))
        render :edit
      end
    end
    redirect_to @meal_plan
  end

  def destroy
    @meal_plan = MealPlan.find(params[:id])
    @meal_plan.destroy

    redirect_to meal_plans_path
  end

  private
    def new_meal_plan_params
      p = params.require(:meal_plan).permit(:date_range_start, :date_range_end)
      if p[:date_range_start] != "" && p[:date_range_end] != ""
        d1 = Date.parse(p[:date_range_start])
        d2 = Date.parse(p[:date_range_end])
        p[:date_range] = d1..d2
      end
      p.delete(:date_range_start)
      p.delete(:date_range_end)
      p
    end
end

app/helpers/meal_plans_helper.rb
module MealPlansHelper
end

app/views/meal_plans/edit.html.erb
<h1>Edit MealPlan <%= @meal_plan.date_range.min %> - <%= @meal_plan.date_range.max %> </h1>

<%= form_with model: @meal_plan do |form| %>
  <% @meal_plan.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
  <p>
    <table>
      <tr>
        <th>Day</th>
        <th>Note</th>
      </tr>
      <% @meal_plan.meal_plan_days.each do |meal_plan_day| %>
        <tr>
          <%= fields_for "meal_plan_day[]", meal_plan_day do |meal_plan_day_fields| %>
            <td><%= meal_plan_day.date %> <%= meal_plan_day.date.strftime("%a") %></td>
            <td><%= meal_plan_day_fields.text_field :note %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/meal_plans/index.html.erb
<h1>MealPlans</h1>

<ul>
  <% @meal_plans.each do |meal_plan| %>
    <li>
      <%= link_to "#{meal_plan.date_range.min} - #{meal_plan.date_range.max}", meal_plan %>
    </li>
  <% end %>
</ul>

<%= link_to "New MealPlan", new_meal_plan_path %>

app/views/meal_plans/new.html.erb
<h1>New MealPlan</h1>

<%= form_with model: @meal_plan do |form| %>
  <% @meal_plan.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
  <p>
    <%= form.label :date_range_start %><br>
    <%= form.date_field :date_range_start, value: @meal_plan.date_range&.min  %>
  </p>

  <p>
    <%= form.label :date_range_end %><br>
    <%= form.date_field :date_range_end, value: @meal_plan.date_range&.max  %><br>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/meal_plans/show.html.erb
<h1>MealPlan <%= @meal_plan.date_range.min %> - <%= @meal_plan.date_range.max %> (<%= link_to "delete", meal_plan_path(@meal_plan), method: :delete %>)</h1>


<h2>Shopping list</h2>
<table>
  <tr>
    <th>Name</th>
    <th>Quantity</th>
  </tr>
  <% @meal_plan.shopping_list_items.each do |shopping_list_item| %>
    <% if shopping_list_item[:shopping_basket_item] %>
      <% if !@hide_items_in_basket %>
        <tr>
          <td><strike><%= shopping_list_item[:food_item_name] %></strike></td>
          <td><strike><%= shopping_list_item[:quantity] %><%= shopping_list_item[:food_item_unit] %></strike></td>
          <td>
            <button>
              <%= link_to "Untick",
                          meal_plan_shopping_basket_item_path(@meal_plan, shopping_list_item[:shopping_basket_item]),
                          method: :delete %>
            </button>
          </td>
        </tr>
      <% end %>
    <% else %>
      <tr>
        <td><%= shopping_list_item[:food_item_name] %></td>
        <td><%= shopping_list_item[:quantity] %><%= shopping_list_item[:food_item_unit] %></td>
        <td>
          <%= form_with model: [@meal_plan, ShoppingBasketItem] do |form| %>
            <%= form.hidden_field :hide_items_in_basket, value: @hide_items_in_basket %>
            <%= form.hidden_field :food_item_id, value: shopping_list_item[:food_item_id] %>
            <%= form.submit "Tick" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>

<% if @hide_items_in_basket %>
  <%= link_to "show items in basket", meal_plan_path(@meal_plan) %>
<% else %>
  <%= link_to "Hide items in basket", meal_plan_path(@meal_plan, hide_items_in_basket: true) %>
<% end %>

<h2>Meals (<%= link_to "edit notes", edit_meal_plan_path(@meal_plan) %>)</h2>
<% @meal_plan.meal_plan_days.each do |meal_plan_day| %>
  <%= render meal_plan_day %>
<% end %>