config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  root "home#index"

  resources :food_items
  resources :meals
  resources :recipes do
    resources :ingredients
  end
  resources :meal_plans do
    resources :meal_plan_days
    resources :shopping_basket_items
  end
  resources :meal_plan_days do
    resources :meals
  end
  post '/meal_plan_days/:id/copy', to: 'meal_plan_days#copy', as: 'copy_meal_plan_day'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, dependent: :destroy

  validates :title, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @food_item_name_query = params[:food_item_name_query]
    @food_item_search_result = FoodItem.find_by(name: @food_item_name_query)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render :edit
    end
  end

  private
    def recipe_params
      params.require(:recipe).permit(:title, :instructions, :calories, :carbs, :protein, :fat)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with model: recipe do |form| %>
  <% recipe.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>

  <p>
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
  </p>

  <h3><%= form.label :instructions %></h3>
  <%= form.text_area :instructions %>

  <h3>Nutrition (per serving)</h3>
  <p>
    <%= form.label :calories %>
    <br>
    <%= form.text_field :calories %>
  </p>
  <p>
    <%= form.label :carbs %>
    <br>
    <%= form.text_field :carbs %>
  </p>
  <p>
    <%= form.label :protein %>
    <br>
    <%= form.text_field :protein %>
  </p>
  <p>
    <%= form.label :fat %>
    <br>
    <%= form.text_field :fat %>
  </p>

  <%= form.submit %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render "form", recipe: @recipe %>

<h3>Ingredients (<%= link_to "add", new_recipe_ingredient_path(@recipe) %>)</h3>
<ul>
  <%= render partial: @recipe.ingredients, locals: {editable: true} %>
</ul>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<ul>
  <% @recipes.each do |recipe| %>
    <li>
      <%= link_to recipe.title, recipe %>
    </li>
  <% end %>
</ul>

<%= link_to "New Recipe", new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render "form", recipe: @recipe %>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %> (<%= link_to "edit", edit_recipe_path(@recipe) %>)</h1>

<h3>Instructions</h3>
<p><%= @recipe.instructions %></p>

<h3>Nutrition (per serving)</h3>
<ul>
  <li>Calories: <%= @recipe.calories %></li>
  <li>Carbs: <%= @recipe.carbs %></li>
  <li>Protein: <%= @recipe.protein %></li>
  <li>Fat: <%= @recipe.fat %></li>
</ul>

<h3>Ingredients</h3>
<ul>
  <%= render partial: @recipe.ingredients, locals: {editable: false} %>
</ul>