config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  root "home#index"

  resources :food_items
  resources :meals
  resources :recipes do
    resources :ingredients
  end
  resources :meal_plans do
    resources :meal_plan_days
    resources :shopping_basket_items
  end
  resources :meal_plan_days do
    resources :meals
  end
  post '/meal_plan_days/:id/copy', to: 'meal_plan_days#copy', as: 'copy_meal_plan_day'
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :food_item
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    @query = params[:query]
    if @query
      @search_results = FoodItem.where("name ILIKE ?", "%#{@query}%")
    end
    if params[:food_item_id]
      @food_item = FoodItem.find(params[:food_item_id])
    end
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = Ingredient.new
    @new_food_item = FoodItem.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    if ingredient_params[:food_item_id] == ""
      food_item = FoodItem.create(food_item_params)
      params[:ingredient][:food_item_id] = food_item.id
    end
    @ingredient = @recipe.ingredients.create(ingredient_params)
    redirect_to edit_recipe_path(@recipe)
  end

  def edit
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.find(params[:id])
    if @ingredient.update(ingredient_params)
      redirect_to edit_recipe_path(@recipe)
    else
      render :edit
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.find(params[:id])
    @ingredient.destroy
    redirect_to edit_recipe_path(@recipe)
  end

  private
    def food_item_params
      params.require(:ingredient).permit(:food_item_name, :food_item_unit)
    end

    def ingredient_params
      params.require(:ingredient).permit(:quantity_per_serving, :food_item_id)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with url: recipe_path(@recipe), method: :get do |form| %>
  <%= form.label :food_item_name_query, "Search for ingredient:" %>
  <%= form.text_field :food_item_name_query, value: @food_item_name_query %>
  <%= form.submit "Search" %>
<% end %>

<%= form_with model: [ @recipe, @recipe.ingredients.build ] do |form| %>
  <%= form.hidden_field :food_item_id, value: @food_item_search_result&.id %>
  <p>
    <%= form.label :food_item_name %><br>
    <%= form.text_field :food_item_name, value: @food_item_search_result&.name %>
  </p>
  <p>
    <%= form.label :quantity_per_serving %><br>
    <%= form.text_field :quantity_per_serving %>
  </p>
  <p>
    <%= form.label :food_item_unit %><br>
    <%= form.text_field :food_item_unit, value: @food_item_search_result&.unit %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/ingredients/_ingredient.html.erb
<li>
  <%= ingredient.food_item.name %>
  <%= ingredient.quantity_per_serving %>
  <%= ingredient.food_item.unit %> 
  <% if editable %>
    <%= link_to "Edit", edit_recipe_ingredient_path(ingredient.recipe, ingredient) %>
    <%= link_to "Remove", recipe_ingredient_path(ingredient.recipe, ingredient), method: :delete %>
  <% end %>
</li>

app/views/ingredients/edit.html.erb
<h1><%= @ingredient.food_item.name %></h1>

<%= form_with model: [ @recipe, @ingredient ] do |form| %>
  <p>
    <%= form.label :quantity_per_serving %><br>
    <%= form.text_field :quantity_per_serving %>
    <%= @ingredient.food_item.unit %>
  </p>
  <p>
    <%= form.submit "Update" %>
  </p>
<% end %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<% if !@food_item %>
  <%= form_with url: new_recipe_ingredient_path, method: :get do |form| %>
    <%= form.label :query, "Search for existing FoodItem" %>
    <%= form.text_field :query, value: @query %>
    <%= form.submit "Search" %>
  <% end %>

  <% if @search_results %>
    <ul>
      <% @search_results.each do |food_item| %>
        <li>
          <%= link_to food_item.name, new_recipe_ingredient_path(food_item_id: food_item.id) %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with model: @new_food_item, url: food_items_path(@new_food_item, redirect: new_recipe_ingredient_path), html: {method: :post} do |form| %>
    Add a new FoodItem:
    <p>
      <%= form.label :unit %>
      <%= form.text_field :unit %>
    </p>
    <p>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
<% else %>
  <%= form_with model: [ @recipe, @ingredient ] do |form| %>
    <%= form.hidden_field :food_item_id, value: @food_item.id %>
    <p><h2><%= @food_item.name %></h2></p>
    <p>
      <%= form.label :quantity_per_serving %><br>
      <%= form.text_field :quantity_per_serving %>
      <%= @food_item.unit %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>
<% end %>