config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  root "home#index"

  resources :food_items
  resources :meals
  resources :recipes do
    resources :ingredients
  end
  resources :meal_plans do
    resources :meal_plan_days
    resources :shopping_basket_items
  end
  resources :meal_plan_days do
    resources :meals
  end
  post '/meal_plan_days/:id/copy', to: 'meal_plan_days#copy', as: 'copy_meal_plan_day'
end

app/models/meal_plan_day.rb
class MealPlanDay < ApplicationRecord
  belongs_to :meal_plan
  has_many :meals, dependent: :destroy

  validates :date, presence: true

  def calories
    result = 0
    self.meals.each do |meal|
      result += meal.recipe.calories
    end
    result
  end

  def carbs
    result = 0
    self.meals.each do |meal|
      result += meal.recipe.carbs
    end
    result
  end

  def protein
    result = 0
    self.meals.each do |meal|
      result += meal.recipe.protein
    end
    result
  end

  def fat
    result = 0
    self.meals.each do |meal|
      result += meal.recipe.fat
    end
    result
  end
end

app/controllers/meal_plan_days_controller.rb
class MealPlanDaysController < ApplicationController
  def show
    @meal_plan_day = MealPlanDay.find(params[:id])
  end

  def copy
    template_mpd = MealPlanDay.find(params[:id])
    template_mpd.meal_plan.meal_plan_days.each { |mpd|
      if mpd.id != template_mpd.id
        mpd.meals.destroy_all
        template_mpd.meals.each { |m|
          cloned = m.dup
          cloned.meal_plan_day = mpd
          cloned.save
        }
      end
    }
    redirect_to template_mpd.meal_plan
  end

  private
    def meal_plan_day_params
      params.require(:meal_plan_day).permit(:note)
    end
end

app/helpers/meal_plan_days_helper.rb
module MealPlanDaysHelper
end

app/views/meal_plan_days/_meal_plan_day.html.erb
<h3>
  <%= link_to meal_plan_day.date, meal_plan_day %>
  <%= meal_plan_day.date.strftime("%a") %>
  <i><%= "(#{meal_plan_day.note})" if meal_plan_day.note != '' %></i>
  (<%= link_to "add meal", new_meal_plan_day_meal_path(meal_plan_day) %>)
  (<%= link_to "copy", copy_meal_plan_day_path(meal_plan_day), method: :post %>)
</h3>
<%= render meal_plan_day.meals.sort_by { |m| m.eat_at } %>

app/views/meal_plan_days/show.html.erb
<h1>MealPlanDay <%= @meal_plan_day.date %></h1>

<p>
  <strong>Calories:</strong>
  <%= @meal_plan_day.calories %>
</p>

<p>
  <strong>Carbs:</strong>
  <%= @meal_plan_day.carbs %>
</p>

<p>
  <strong>Protein:</strong>
  <%= @meal_plan_day.protein %>
</p>

<p>
  <strong>Fat:</strong>
  <%= @meal_plan_day.fat %>
</p>